// <auto-generated />
namespace NextLAP.IP1.Storage.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedconfigurationtoequipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedconfigurationtoequipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201507281012171_Added configuration to equipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
