// <auto-generated />
namespace NextLAP.IP1.Storage.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedequipmententities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedequipmententities));
        
        string IMigrationMetadata.Id
        {
            get { return "201506251502585_Added equipment entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
